/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./src/components/Board/Board.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu/ContextMenu.vue')['default']
    ExportMenu: typeof import('./src/components/Header/ExportMenu.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    MinorTool: typeof import('./src/components/ToolBar/MinorTool.vue')['default']
    Modal: typeof import('./src/components/Modal/Modal.vue')['default']
    PropertiesPanel: typeof import('./src/components/PropertiesPanel/PropertiesPanel.vue')['default']
    ShapesTool: typeof import('./src/components/ToolBar/ShapesTool.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    TemplatesPanel: typeof import('./src/components/TemplateTool/templatesPanel.vue')['default']
    TemplateTool: typeof import('./src/components/TemplateTool/TemplateTool.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar/ToolBar.vue')['default']
    ZoomTool: typeof import('./src/components/Header/ZoomTool.vue')['default']
  }
}
